name: Build Bot
on:
    push:
        branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    name: Build Bot
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build --if-present
      #- run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: deploy using SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/home/runner/Bot207/
          git pull origin main
          git status
          npm install --only=prod
          npm run build
          pm2 restart Bot207