name: CI
​
on:
    push:
        branches: [ master ]
    
jobs:
    deploy:
        runs-on: self-hosted
    
    strategy: 
        matrix:
            node-version: [12.x]
            
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
          with:
          node-version: '18.x'
    # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.
          check-latest: true
          cache: 'npm'
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: # optional
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
